services:
  db:
    image: postgres:16
    container_name: uni_apply_db
    environment:
      POSTGRES_DB: uni_apply
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - uni_apply_pgdata:/var/lib/postgresql/data

volumes:
  uni_apply_pgdata: